version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./src:/var/www/html

